### ISSUE TITLE
What fuse library?

### ISSUE THREAD

**Issue by JHerseth** [acenko/FLACCue#5]
Hey, so I'm finally on a nix system so I thought I'd get this up and running (man how much nicer it is to have all my media stuff in docker containers).

I'm trying to get this running now, and I've installed the requirements like mutagen etc, and a couple of fuse libraries. I've tried both pyfuse3 and fuse-python, but seems like those are the wong ones.  Can you point me to the right one?

**Comment by acenko** [comment]
So there are two components to FUSE:
1. You need to ensure libfuse is available in your Linux install. You can check for /usr/lib/libfuse.so on your system, although it may be installed in different locations for different distributions. You may need to add libfuse through your Linux package manager. At worst, you should be able to build it from the [source project](https://github.com/libfuse/libfuse) but only do this as a last resort.
2. You will need a Python interface to the fuse library. The simplest option here would be to use [the copy I used in the Synology package](https://github.com/acenko/FLACCue/blob/master/synology_package/FLACCue/fuse.py).

The Synology package scripts may also be useful to see how things run there. The most useful would likely be the [postinst script](https://github.com/acenko/FLACCue/blob/master/synology_package/FLACCue/scripts/postinst) (which initializes the expected directories and paths for the package) and the [start-stop-status script](https://github.com/acenko/FLACCue/blob/master/synology_package/FLACCue/scripts/start-stop-status).

If none of these options help, it would be useful to see any errors you're getting.

**Comment by JHerseth** [comment]
Ok, so I got things working with the synology package. Thanks for the help. Sorry to bother you some more.... I try to run 
`./FLACCue /media/media3/Music/Haken/2016\ Affinity/Haken\ -\ Affinity\ \(Disc\ 1\).cue rootdir` - the rootdir directory disappears from the flaccue dir where it was, and in nemo I get a new mounted disc called rootdir. clicking this gives me an error that files cannot be displayed: not a directory. Any idea what's going on?

**Comment by acenko** [comment]
So the FLACCue command mounts a FUSE filesystem that mirrors the first argument to the second location. In this case, you are mounting a file to a directory. As an example based on yours, you would run
`./FLACCue /media/media3/Music/Haken/2016\ Affinity/ rootdir`
and then find "Haken\ -\ Affinity\ \(Disc\ 1\).cue" within rootdir.

I suspect you actually want to run something more like:
`./FLACCue /media/media3/Music/ rootdir`
which would mount the full Music directory at rootdir, with the extra FLACCue processing available. You would then use the FLACCue scanner in Plex to scan the files in rootdir and it would automatically extract the tracks from any .cue files in the directory structure and provide the correct filesystem requests to extract the tracks when accessed through Plex.

Does this make sense?

**Comment by JHerseth** [comment]
Thank you for your patience :) Everything makes sense now. I've mounted the music dir, and set up the scanner, and it's working without a hitch! Now I just have to figure out how to modify my plex docker image to include FLACCue. I won't bother you with that though.

Thanks again!
